language: php

php:
  - 7.1

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry pecl install ldap

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - cat composer.lock
