language: php

php:
  - 7.0
 # - 5.6
 # - 5.5

install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer update

after_script:
  - cat composer.json
  - cat composer.lock
