language: php

php:
  - 7.0
 # - 5.6
 # - 5.5

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"

before_script:
  - travis_retry composer update

after_script:
  - cat composer.json
  - cat composer.lock
