language: php

php:
  - 7.1

before_install: 
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - cat composer.lock
