language: php

php:
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"

before_script:
  - travis_retry composer update

script:
  - cat composer.lock
